# Generated by Django 3.1.4 on 2021-01-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_id', models.CharField(max_length=11)),
                ('full_name', models.CharField(max_length=25)),
                ('espn_name', models.CharField(max_length=20)),
            ],
        ),
    ]
