# Generated by Django 5.0.6 on 2024-05-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0003_tag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='No Title', max_length=50),
        ),
    ]
