# Generated by Django 5.0.6 on 2024-06-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0008_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='content',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
